"""
main.py
=======
Phase F: Eco-Twin Oracle — FastAPI Interoperability Layer

Exposes the full Oracle pipeline via:
  • WebSocket  /ws/live-batch/{batch_id}   — real-time streaming inference
  • REST GET   /api/v1/active-prescriptions — latest validated setpoints (Swagger)
  • REST GET   /api/v1/dfa-state            — current DFA state for any active batch
  • REST GET   /health                      — liveness probe

Design notes
────────────
• The SOM and LVQ are trained ONCE during server startup using data from all
  available batch sheets, via FastAPI's async lifespan context manager.
  A dummy initialisation fallback guarantees the server starts even if the
  Excel file is absent (e.g., CI environment).
• All analytics objects (SOM, LVQ, DFA) are stored on app.state so they are
  accessible from any endpoint without globals or module-level side-effects.
• Streaming WebSocket payload is a structured JSON envelope.
• The /docs Swagger UI is auto-generated by FastAPI from Pydantic response models.
"""

from __future__ import annotations

import asyncio
import json
import logging
import time
from contextlib import asynccontextmanager
from dataclasses import asdict
from typing import Any, Optional

import numpy as np
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from analytics_engine import (
    FEATURE_COLUMNS,
    KohonenSOM,
    LVQClassifier,
    PhantomEnergyAlert,
    Prescription,
    _telemetry_to_vector,
    detect_phantom_energy,
    generate_prescription,
    analyze_spectral_friction,
    detect_inter_phase_arbitrage,
    generate_xai_reasoning,
    evaluate_batch_performance,
)
from schemas import BatchTelemetry
from state_machine import DFAStateMachine, ManufacturingPhase
from stream_simulator import EXCEL_PATH, PHASE_STRING_TO_ENUM, stream_batch_data

# ──────────────────────────────────────────────────────────────────────────────
# Logging
# ──────────────────────────────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("eco_twin_oracle")

# ──────────────────────────────────────────────────────────────────────────────
# Pydantic Response Models  (FastAPI needs BaseModel, not dataclass, for /docs)
# ──────────────────────────────────────────────────────────────────────────────

class PrescriptionResponse(BaseModel):
    """
    Pydantic response schema for a validated prescriptive recommendation.
    Mirrors the analytics_engine.Prescription dataclass for Swagger generation.
    """
    batch_id: str = Field(..., description="Batch identifier, e.g. T060")
    time_minutes: int = Field(..., ge=0, description="Elapsed minutes in batch lifecycle")
    dfa_state: str = Field(..., description="Current DFA phase name")
    bmu_index: list[int] = Field(..., description="[row, col] coordinates of the Best Matching Unit on the SOM lattice")
    bmu_distance: float = Field(..., ge=0.0, description="Euclidean distance from live vector to BMU (lower = closer to Golden Signature)")
    anomaly_class: str = Field(..., description="LVQ anomaly classification label")
    parameter_recommendations: dict[str, float] = Field(
        ..., description="DFA-validated parameter deltas: keys are telemetry fields, values are suggested adjustment magnitudes"
    )
    dfa_guardrail_passed: bool = Field(..., description="True if no parameters were blocked by the DFA transition matrix")
    blocked_parameters: list[str] = Field(
        default_factory=list,
        description="Parameters the DFA guardrail rejected as chronologically impossible"
    )

    @classmethod
    def from_dataclass(cls, p: Prescription) -> "PrescriptionResponse":
        return cls(
            batch_id=p.batch_id,
            time_minutes=p.time_minutes,
            dfa_state=p.dfa_state,
            bmu_index=list(p.bmu_index),
            bmu_distance=p.bmu_distance,
            anomaly_class=p.anomaly_class,
            parameter_recommendations=p.parameter_recommendations,
            dfa_guardrail_passed=p.dfa_guardrail_passed,
            blocked_parameters=p.blocked_parameters,
        )


class PhantomAlertResponse(BaseModel):
    """Pydantic mirror of the PhantomEnergyAlert dataclass for JSON serialisation."""
    batch_id: str
    time_minutes: int
    dfa_state: str
    motor_speed_rpm: int
    power_consumption_kw: float
    message: str
    severity: str

    @classmethod
    def from_dataclass(cls, a: PhantomEnergyAlert) -> "PhantomAlertResponse":
        return cls(**asdict(a))


class DFAStateResponse(BaseModel):
    """Live DFA state snapshot for a given batch."""
    batch_id: str
    dfa_state: str
    dfa_phase_number: int
    is_terminal: bool


class HealthResponse(BaseModel):
    """Liveness probe response."""
    status: str
    som_trained: bool
    lvq_trained: bool
    uptime_seconds: float


class WebSocketPayload(BaseModel):
    """Full JSON envelope pushed to WebSocket clients on every telemetry tick."""
    event: str  # "telemetry" | "phantom_energy" | "batch_complete" | "error"
    telemetry: Optional[dict[str, Any]] = None
    dfa_state: Optional[str] = None
    prescription: Optional[dict[str, Any]] = None
    phantom_alert: Optional[dict[str, Any]] = None
    pvr_alert: Optional[dict[str, Any]] = None
    arbitrage_alert: Optional[dict[str, Any]] = None
    xai_data: Optional[dict[str, Any]] = None
    quality_margin: float = 0.0
    timestamp_ms: int = 0


# ──────────────────────────────────────────────────────────────────────────────
# Startup Training
# ──────────────────────────────────────────────────────────────────────────────

def _build_dummy_training_data(n_samples: int = 50) -> tuple[np.ndarray, np.ndarray]:
    """
    Fallback: generate synthetic training data shaped like real telemetry
    so the server can boot without the Excel file present (e.g., in CI).
    """
    rng = np.random.default_rng(0)
    X = rng.uniform(
        low=[20, 1.0, 30, 0, 0, 0, 1.0, 0.05],
        high=[80, 5.0, 70, 300, 50, 20, 8.0, 0.5],
        size=(n_samples, len(FEATURE_COLUMNS)),
    )
    y = np.array(["Normal"] * n_samples)
    return X, y


# Top-tier batch IDs (Dissolution_Rate >= 95%) used to build the Golden Signature.
# This ensures the SOM learns ONLY from the best-performing batches — deviations
# from this optimum are what create meaningful anomaly signals for weaker batches.
GOLDEN_BATCH_IDS: set[str] = set()  # Populated at startup from production data


def _identify_golden_batches() -> set[str]:
    """
    Read the production dataset to identify top-tier batches (Dissolution_Rate >= 95%).
    These batches form the Golden Signature training corpus.
    """
    import pandas as pd
    import os

    prod_path = "_h_batch_production_data.xlsx"
    if not os.path.exists(prod_path):
        logger.warning("Production data not found. Using all batches for training.")
        return set()

    try:
        prod_df = pd.read_excel(prod_path, sheet_name="BatchData")
        top_batches = prod_df[prod_df["Dissolution_Rate"] >= 95.0]["Batch_ID"].tolist()
        logger.info(
            "Golden Batch Selection: %d of %d batches have Dissolution_Rate >= 95%% → %s",
            len(top_batches), len(prod_df), top_batches,
        )
        return set(top_batches)
    except Exception as exc:
        logger.warning("Failed to read production data: %s. Using all batches.", exc)
        return set()


async def _train_from_excel() -> tuple[np.ndarray, np.ndarray]:
    """
    Collect multivariate feature vectors ONLY from top-performing batches
    (Dissolution_Rate >= 95%) to build a Golden Signature training corpus.

    This is the critical fix: training on ALL batches (including bad ones)
    creates an 'average' signature, not a 'golden' one. By training only on
    top-tier batches, bad batches will show high BMU distance (far from golden)
    and good batches will show low BMU distance (close to golden).

    Runs in a threadpool executor so the async event loop stays unblocked.
    """
    import pandas as pd
    import os

    if not os.path.exists(EXCEL_PATH):
        logger.warning("Excel file not found at '%s'. Using dummy training data.", EXCEL_PATH)
        return _build_dummy_training_data()

    def _read_excel_sync() -> tuple[np.ndarray, np.ndarray]:
        global GOLDEN_BATCH_IDS
        GOLDEN_BATCH_IDS = _identify_golden_batches()
        
        xl = pd.ExcelFile(EXCEL_PATH)
        golden_rows, all_rows = [], []
        all_labels = []
        golden_count, total_count = 0, 0
        
        for sheet in xl.sheet_names:
            try:
                df = xl.parse(sheet).sort_values("Time_Minutes")
                batch_id = str(df["Batch_ID"].iloc[0]).strip()
                is_golden = batch_id in GOLDEN_BATCH_IDS or len(GOLDEN_BATCH_IDS) == 0
                
                for _, row in df.iterrows():
                    vec = [
                        float(row.get(col, 0.0))
                        for col in FEATURE_COLUMNS
                    ]
                    all_rows.append(vec)
                    all_labels.append("Normal")
                    
                    if is_golden:
                        golden_rows.append(vec)
                        golden_count += 1
                    
                total_count += len(df)
            except Exception as exc:
                logger.debug("Skipping sheet '%s': %s", sheet, exc)
        
        # Use golden rows for SOM, all rows for LVQ
        som_data = np.array(golden_rows, dtype=np.float64) if golden_rows else np.array(all_rows, dtype=np.float64)
        lvq_data = np.array(all_rows, dtype=np.float64)
        
        logger.info(
            "SOM training: %d golden rows from %d top batches. LVQ training: %d total rows.",
            len(som_data), len(GOLDEN_BATCH_IDS), len(lvq_data),
        )
        return som_data, lvq_data

    som_X, lvq_X = await asyncio.to_thread(_read_excel_sync)
    logger.info("Training corpus loaded: SOM=%d golden rows, LVQ=%d total rows.", len(som_X), len(lvq_X))
    # Return SOM data as X and LVQ data packed as labels (we'll unpack in lifespan)
    # Store LVQ data on a module-level variable for the lifespan to use
    global _lvq_training_data
    _lvq_training_data = lvq_X
    return som_X, np.array(["Normal"] * len(som_X))

# Module-level storage for LVQ training data (populated by _train_from_excel)
_lvq_training_data: np.ndarray | None = None


def _build_lvq_labels(X: np.ndarray, rng_seed: int = 42) -> np.ndarray:
    """
    Heuristically label the training data for LVQ using physical rules so the
    classifier has multi-class signal even before operator feedback is collected.

    Thresholds are calibrated from actual dataset analysis:
      - Avg vibration ~3.0 mm/s, range 0.05-11+ mm/s
      - Avg power ~23 kW, range 0.5-70 kW  
      - Avg temp ~35°C, range 20-65°C
      - Avg pressure ~2.5 bar, range 0.5-5+ bar

    Rules (calibrated to real data distribution):
      - Vibration > 5.0 mm/s + Power > 35 kW   → "Mechanical Friction"
      - Vibration > 5.0 mm/s                    → "Vibration Fatigue"
      - Temperature spike (> 55 °C)             → "Thermal Drift"
      - Pressure spike (> 4.0 bar)              → "Pressure Surge"
      - RPM > 0 and Flow < 2 LPM               → "Flow Stagnation"
      - Everything else                          → "Normal"
    """
    # Column index shortcuts (matches FEATURE_COLUMNS order)
    # [Temp, Pressure, Humidity, RPM, Compression, Flow, Power, Vibration]
    TEMP_IDX, PRESS_IDX = 0, 1
    RPM_IDX, FLOW_IDX, POWER_IDX, VIB_IDX = 3, 5, 6, 7

    labels = []
    for row in X:
        if row[VIB_IDX] > 5.0 and row[POWER_IDX] > 35.0:
            labels.append("Mechanical Friction")
        elif row[VIB_IDX] > 5.0:
            labels.append("Vibration Fatigue")
        elif row[TEMP_IDX] > 55.0:
            labels.append("Thermal Drift")
        elif row[PRESS_IDX] > 4.0:
            labels.append("Pressure Surge")
        elif row[RPM_IDX] > 0 and row[FLOW_IDX] < 2.0:
            labels.append("Flow Stagnation")
        else:
            labels.append("Normal")
    return np.array(labels)


# ──────────────────────────────────────────────────────────────────────────────
# FastAPI Lifespan — trains models once at server start
# ──────────────────────────────────────────────────────────────────────────────

_server_start_time = time.monotonic()

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Async lifespan context manager.  Runs training before the server
    accepts connections, guarantees clean teardown on shutdown.
    """
    logger.info("=" * 60)
    logger.info("  Eco-Twin Oracle — Initialising AI Engine")
    logger.info("=" * 60)
    
    # ── Auto-calibrate thresholds ──────────────────────────────────────────
    import analytics_engine
    await asyncio.to_thread(analytics_engine.auto_calibrate_thresholds)
    logger.info(f"Thresholds Calibrated: AVG={analytics_engine.GOLDEN_AVG_POWER_THRESHOLD:.2f}kW, PEAK={analytics_engine.GOLDEN_PEAK_POWER_THRESHOLD:.2f}kW")

    # ── Load training data ─────────────────────────────────────────────────
    # _train_from_excel now returns ONLY golden batch data for SOM
    # and stores ALL batch data in _lvq_training_data for LVQ
    X_som, _ = await _train_from_excel()
    
    # LVQ trains on ALL data (so it understands both normal and anomalous patterns)
    X_lvq = _lvq_training_data if _lvq_training_data is not None else X_som
    y_train = _build_lvq_labels(X_lvq)

    # ── Train SOM (Golden Signature topology) ──────────────────────────────
    # SOM trains ONLY on top-tier batches → the "golden" operating region
    som = KohonenSOM(grid_h=10, grid_w=10, n_iterations=800, seed=42)
    t0 = time.monotonic()

    await asyncio.to_thread(som.fit, X_som)
    logger.info("KohonenSOM trained in %.2fs on %d GOLDEN samples (10×10 grid).", time.monotonic() - t0, len(X_som))

    # ── Train LVQ (Anomaly Classifier) ────────────────────────────────────
    # LVQ trains on ALL data so it sees the full spectrum of anomaly classes
    lvq = LVQClassifier(n_prototypes_per_class=3, learning_rate=0.05, n_epochs=400, seed=42)
    t0 = time.monotonic()
    await asyncio.to_thread(lvq.fit, X_lvq, y_train)
    logger.info("LVQClassifier trained in %.2fs on %d samples. Classes: %s", time.monotonic() - t0, len(X_lvq), list(np.unique(y_train)))

    # ── Attach to app state ────────────────────────────────────────────────
    app.state.som = som
    app.state.lvq = lvq
    app.state.active_prescriptions = {}
    app.state.active_dfa_states = {}

    logger.info("Oracle engine ready. Swagger UI: http://localhost:8000/docs")
    logger.info("=" * 60)

    yield  # ── Server is live ──────────────────────────────────────────────

    logger.info("Eco-Twin Oracle shutting down gracefully.")


# ──────────────────────────────────────────────────────────────────────────────
# FastAPI Application
# ──────────────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Eco-Twin Oracle API",
    description=(
        "**Prescriptive Manufacturing Intelligence** — AVEVA Hackathon Track B.\n\n"
        "Real-time batch process optimisation powered by:\n"
        "- 🤖 **Kohonen Self-Organising Maps** for Golden Signature topology\n"
        "- 🔬 **Learning Vector Quantisation** for anomaly classification\n"
        "- 🔒 **Deterministic Finite Automaton (DFA)** as mathematical guardrail against AI hallucination\n"
        "- ⚡ **Phantom Energy Detection** for idle-phase waste identification\n\n"
        "Stream live telemetry via WebSocket `/ws/live-batch/{batch_id}` or query "
        "the latest optimal setpoints via the REST endpoints below."
    ),
    version="1.0.0",
    contact={
        "name": "Team SpicyJalebi",
        "email": "team@eco-twin-oracle.ai",
    },
    license_info={"name": "MIT"},
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
)

# Allow all origins during hackathon demo (tighten in production)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ──────────────────────────────────────────────────────────────────────────────
# REST Endpoints
# ──────────────────────────────────────────────────────────────────────────────

@app.get(
    "/health",
    response_model=HealthResponse,
    tags=["System"],
    summary="Liveness probe",
)
async def health_check() -> HealthResponse:
    """Returns server liveness status and model readiness."""
    return HealthResponse(
        status="healthy",
        som_trained=app.state.som.is_trained,
        lvq_trained=app.state.lvq.is_trained,
        uptime_seconds=round(time.monotonic() - _server_start_time, 2),
    )


@app.get(
    "/api/v1/active-prescriptions",
    response_model=list[PrescriptionResponse],
    tags=["Optimization Engine"],
    summary="Get latest optimal machine setpoints for all active batches",
    response_description=(
        "List of DFA-validated prescriptive recommendations. Each entry represents "
        "the most recent Golden Signature delta computed for a streaming batch."
    ),
)
async def get_active_prescriptions() -> list[PrescriptionResponse]:
    """
    Exposes the current optimal setpoints for all active streaming batches.

    The DFA guardrail guarantees every recommendation is chronologically
    feasible — no parameter from a past physical phase will appear here.

    This endpoint drives the Swagger `/docs` interoperability scoring requirement.
    """
    return list(app.state.active_prescriptions.values())


@app.get(
    "/api/v1/dfa-state/{batch_id}",
    response_model=DFAStateResponse,
    tags=["DFA State Machine"],
    summary="Query the current DFA phase for a streaming batch",
)
async def get_dfa_state(batch_id: str) -> DFAStateResponse:
    """
    Returns the live Deterministic Finite Automaton state for *batch_id*.

    Returns 404 if the batch is not currently streaming.
    """
    from fastapi import HTTPException
    state = app.state.active_dfa_states.get(batch_id)
    if state is None:
        raise HTTPException(
            status_code=404,
            detail=f"Batch '{batch_id}' is not currently active. Start it via the WebSocket endpoint.",
        )
    return state


@app.get(
    "/api/v1/phases",
    response_model=list[dict],
    tags=["DFA State Machine"],
    summary="List all 8 manufacturing phases in DFA transition order",
)
async def get_phases() -> list[dict]:
    """Returns the complete ordered list of DFA states for the manufacturing process."""
    return [
        {
            "phase_number": phase.value,
            "phase_name": phase.name,
            "csv_label": csv_key,
            "is_terminal": phase == ManufacturingPhase.QUALITY_TESTING,
        }
        for csv_key, phase in PHASE_STRING_TO_ENUM.items()
    ]


# ──────────────────────────────────────────────────────────────────────────────
# WebSocket Endpoint — Real-Time Streaming Pipeline
# ──────────────────────────────────────────────────────────────────────────────

@app.websocket("/ws/live-batch/{batch_id}")
async def websocket_live_batch(websocket: WebSocket, batch_id: str):
    """
    WebSocket endpoint for real-time batch telemetry streaming.

    Protocol
    ────────
    1. Client connects to ws://host/ws/live-batch/{batch_id}
    2. Server begins streaming (BatchTelemetry, DFA state, Prescription) tuples at
       ~5 ticks/second (200ms simulated latency per row).
    3. On each tick a JSON payload is pushed:
         {
           "event":        "telemetry" | "phantom_energy",
           "telemetry":    { ...BatchTelemetry fields... },
           "dfa_state":    "GRANULATION",
           "prescription": { ...PrescriptionResponse fields... },
           "phantom_alert": null | { ...PhantomAlertResponse fields... },
           "pvr_alert": null | { ... },
           "arbitrage_alert": null | { ... },
           "xai_data": null | { ... },
           "quality_margin": 1.25,
           "timestamp_ms": 1709999999000
         }
    4. When the batch is exhausted a {"event": "batch_complete"} frame is sent
       and the connection is closed cleanly.
    5. Any unhandled error sends {"event": "error", "detail": "..."} before close.
    """
    await websocket.accept()
    logger.info("[WS] Client connected for batch '%s'.", batch_id)

    som: KohonenSOM = app.state.som
    lvq: LVQClassifier = app.state.lvq
    dfa = DFAStateMachine()  # Fresh DFA per batch lifecycle

    power_history: list[float] = []
    bmu_distances: list[float] = []
    anomaly_classes: list[str] = []
    total_phantom = 0
    total_pvr = 0
    total_arbitrage = 0

    try:
        async for telemetry, current_phase, quality_margin in stream_batch_data(batch_id, tick_delay=0.0):
            power_history.append(telemetry.Power_Consumption_kW)

            # ── Novel Detectors ──────────────────────────────────────────
            pvr_alert = analyze_spectral_friction(telemetry)
            arbitrage_alert = detect_inter_phase_arbitrage(telemetry, current_phase)

            # ── Phantom energy detection ─────────────────────────────────
            phantom_alert: Optional[PhantomEnergyAlert] = detect_phantom_energy(
                telemetry, current_phase
            )

            # ── Prescriptive recommendation (DFA-guarded) ────────────────
            prescription: Prescription = generate_prescription(
                telemetry, current_phase, som, lvq, dfa, quality_margin
            )
            prescription_resp = PrescriptionResponse.from_dataclass(prescription)

            # ── Generate XAI Reasoning ────────────────────────────────────
            xai_data = generate_xai_reasoning(telemetry, prescription.anomaly_class, current_phase)

            # ── Update shared app state for REST polling ──────────────────
            app.state.active_prescriptions[batch_id] = prescription_resp
            app.state.active_dfa_states[batch_id] = DFAStateResponse(
                batch_id=batch_id,
                dfa_state=current_phase.name,
                dfa_phase_number=current_phase.value,
                is_terminal=(current_phase == ManufacturingPhase.QUALITY_TESTING),
            )

            # ── Build JSON envelope ───────────────────────────────────────
            has_anomaly = prescription.anomaly_class != "Normal"
            has_phantom = phantom_alert is not None
            has_pvr = pvr_alert is not None
            has_arbitrage = arbitrage_alert is not None
            
            # Track cumulative stats for batch summary
            bmu_distances.append(prescription.bmu_distance)
            anomaly_classes.append(prescription.anomaly_class)
            if has_phantom: total_phantom += 1
            if has_pvr: total_pvr += 1
            if has_arbitrage: total_arbitrage += 1
            
            # Determine event type based on severity priority
            if has_phantom:
                event_type = "phantom_energy"
            elif has_anomaly:
                event_type = "anomaly_detected"
            elif has_pvr or has_arbitrage:
                event_type = "process_alert"
            else:
                event_type = "telemetry"
            
            payload = {
                "event": event_type,
                "telemetry": telemetry.model_dump(),
                "dfa_state": current_phase.name,
                "prescription": prescription_resp.model_dump(),
                "phantom_alert": (
                    PhantomAlertResponse.from_dataclass(phantom_alert).model_dump()
                    if phantom_alert else None
                ),
                "pvr_alert": pvr_alert,
                "arbitrage_alert": arbitrage_alert,
                "xai_data": xai_data,
                "quality_margin": quality_margin,
                # Alert flags for frontend counting
                "has_anomaly": has_anomaly,
                "has_phantom": has_phantom,
                "has_pvr_alert": has_pvr,
                "has_arbitrage_alert": has_arbitrage,
                "timestamp_ms": int(time.time() * 1000),
            }

            await websocket.send_text(json.dumps(payload))

            # ── Simulated 200ms real-time latency ─────────────────────────
            await asyncio.sleep(1.5)

        # Calculate both average AND peak power
        avg_batch_power = sum(power_history) / len(power_history) if power_history else 0
        max_batch_power = max(power_history) if power_history else 0
        
        # Run the upgraded strict evaluation
        ledger_result = evaluate_batch_performance(batch_id, avg_batch_power, max_batch_power)
        
        # Build anomaly summary for the frontend
        anomaly_count = sum(1 for c in anomaly_classes if c != "Normal")
        class_counts = {}
        for c in anomaly_classes:
            class_counts[c] = class_counts.get(c, 0) + 1
        # Find the dominant non-Normal class
        non_normal = {k: v for k, v in class_counts.items() if k != "Normal"}
        dominant_anomaly = max(non_normal, key=non_normal.get) if non_normal else "Normal"
        
        import numpy as np
        avg_bmu = float(np.mean(bmu_distances)) if bmu_distances else 0.0
        max_bmu = float(np.max(bmu_distances)) if bmu_distances else 0.0
        
        batch_summary = {
            "total_rows": len(power_history),
            "total_alerts": anomaly_count + total_phantom + total_pvr + total_arbitrage,
            "anomaly_detections": anomaly_count,
            "phantom_alerts": total_phantom,
            "pvr_alerts": total_pvr,
            "arbitrage_alerts": total_arbitrage,
            "dominant_anomaly": dominant_anomaly,
            "anomaly_class_counts": class_counts,
            "avg_bmu_distance": round(avg_bmu, 4),
            "max_bmu_distance": round(max_bmu, 4),
            "normal_pct": round(class_counts.get("Normal", 0) / len(anomaly_classes) * 100, 1) if anomaly_classes else 0,
        }
        
        # Send payload
        await websocket.send_json({
            "event": "batch_complete",
            "ledger_status": ledger_result,
            "batch_summary": batch_summary,
        })
        logger.info("[WS] Batch '%s' stream complete. Ledger Status: %s", batch_id, ledger_result["trigger_som_retraining"])

    except WebSocketDisconnect:
        logger.info("[WS] Client disconnected from batch '%s'.", batch_id)

    except FileNotFoundError as exc:
        await websocket.send_text(json.dumps({
            "event": "error",
            "detail": str(exc),
            "timestamp_ms": int(time.time() * 1000),
        }))
        logger.error("[WS] Batch '%s' not found: %s", batch_id, exc)

    except Exception as exc:
        logger.exception("[WS] Unhandled error for batch '%s': %s", batch_id, exc)
        try:
            await websocket.send_text(json.dumps({
                "event": "error",
                "detail": f"Internal Oracle error: {type(exc).__name__}: {exc}",
                "timestamp_ms": int(time.time() * 1000),
            }))
        except Exception:
            pass  # Client may have already disconnected

    finally:
        # Clean up active state when stream ends
        app.state.active_prescriptions.pop(batch_id, None)
        app.state.active_dfa_states.pop(batch_id, None)


# ──────────────────────────────────────────────────────────────────────────────
# Dev server entry point
# ──────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=8000,
        reload=False,        # Keep False — reload breaks lifespan training state
        log_level="info",
    )
